version: 1
formatters:
  logging_format:
    class: pythonjsonlogger.json.JsonFormatter
    format: "%(asctime)s.%(msecs)03d %(levelname)s %(filename)s:%(funcName)s:%(lineno)d %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: logging_format
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: logging_format
    filename: "./logs/mitigator.log"
    maxBytes: 10485760 # 10MB
    mode: a # append
    backupCount: 9
    encoding: utf-8
loggers:
  oqtopus_engine_mitigator:
    level: DEBUG
    handlers: [console, file]
    propagate: False
root:
  level: WARNING
  handlers: [console, file]
disable_existing_loggers: False
